#!/usr/bin/env bash
sudo apt install software-properties-common
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install ansible
echo "Do you want to pull ansible.git? (y/N) "
read answer

if [[ "$answer" == "y" ||  "answer" ==  "Y" ]]; then
    sudo ansible-pull -U https://github.com/duu261/ansible.git
    echo "Installation completed, pulled ansible.git"
else
    echo "Installation completed, skipping pull"
fi
