---
- name: Install dev packages
  become: true
  ansible.builtin.package:
    state: present
    name:
      - base-devel
      - jq
      - xdg-user-dirs
      - neovim
      - yq
      - unzip
      - wget
      - ripgrep
      - fd
      - github-cli
      - luarocks
      - lua51
      - ninja
      - jdk17-openjdk
      - htop
      - npm
      - starship
      - fzf
      - zoxide
      - vivid
      - thefuck
      - tmux
      - bat
      - eza
      - tealdeer
      - lazygit
      - yazi
      - tmux
      - 7zip

- name: Install yazi flavors
  become: true
  command: ya pack -a yazi-rs/flavors:catppuccin-macchiato
- name: Install bat flavors
  become: true
  command: bat cache --build
- name: Install user dirs
  command: xdg-user-dirs-update
# - name: Install linters
#   become: true
#   ansible.builtin.package:
#     state: present
#     name:
#       - codespell
#       - shellcheck

- name: Install yay
  aur:
    name: yay-bin
# - name: Install tools
#   aur:
#     name:
#       - readability-cli
#       - hadolint-bin
