- name: Clone vscode-gradle
  git:
    repo: https://github.com/microsoft/vscode-gradle
    dest: ~/dev/microsoft/vscode-gradle
    force: true

- name: Build vscode-gradle
  command: ./gradlew :gradle-language-server:distTar
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
  args:
    chdir: ~/dev/microsoft/vscode-gradle

- name: Extract gradle-language-server distTar
  unarchive:
    src: ~/dev/microsoft/vscode-gradle/gradle-language-server/build/distributions/gradle-language-server.tar
    dest: ~/dev/microsoft/vscode-gradle/build/
    remote_src: true
