---
- name: Add aur module
  hosts: localhost
  tasks:
  - name: Create modules folder
    ansible.builtin.file:
      state: directory
      recurse: true
      path: ~/.ansible/plugins/modules

  - name: Install ansible aur helper
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/kewlfft/ansible-aur/master/plugins/modules/aur.py
      dest: ~/.ansible/plugins/modules/aur.py
      mode: 0644
